Update update_sqlite_bindings.yml (#14)
* Update update_sqlite_bindings.yml

* Update update_sqlite_bindings.yml

* Update update_sqlite_bindings.yml

* Update update_sqlite_bindings.yml

* Update update_sqlite_bindings.yml

---------

Co-authored-by: Taras Mazepa <6552358+TarasMazepa@users.noreply.github.com>

diff --git a/.github/workflows/update_sqlite_bindings.yml b/.github/workflows/update_sqlite_bindings.yml
--- a/.github/workflows/update_sqlite_bindings.yml
+++ b/.github/workflows/update_sqlite_bindings.yml
@@ -14,7 +14,7 @@ jobs:
       - name: Prepare for ffi gen
         id: prepare
         run: |
-          URL="https://www.sqlite.org/$(curl -s https://www.sqlite.org/download.html | grep PRODUCT | grep sqlite-amalgamation | sed 's/[^,]*,[^,]*,\([^,]*\),.*/\1/')"
+          URL="https://sqlite.org/$(curl -s https://sqlite.org/download.html | grep PRODUCT | grep sqlite-amalgamation | sed 's/[^,]*,[^,]*,\([^,]*\),.*/\1/')"
           VERSION=$(echo $URL | sed 's/.*-//' | sed 's/.zip//')
           echo "Latest SQLite download url: $URL"
           echo "Latest SQLite version: $VERSION"
@@ -24,8 +24,22 @@ jobs:
 
           mkdir -p sqliteraw/.sqlite-source-code
           cd sqliteraw/.sqlite-source-code
-          curl -o sqlite.zip $URL
-          unzip -j sqlite.zip *sqlite3.h
+          curl -L -o sqlite.zip $URL
+          if [ ! -f sqlite.zip ]; then
+            echo "Failed to download SQLite"
+            exit 1
+          fi
+          
+          if ! unzip -j sqlite.zip "*sqlite3.h"; then
+            echo "Failed to unzip SQLite"
+            exit 1
+          fi
+          
+          if [ ! -f sqlite3.h ]; then
+            echo "sqlite3.h not found after unzip"
+            exit 1
+          fi
+          
           pwd
           ls
 
